//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitTablosuu
    {
        public int Id { get; set; }
        public string TeslimAdresi { get; set; }
        public string IkıncıAdres { get; set; }
        public string PaketIcerigi { get; set; }
        public Nullable<double> KuryeUcreti { get; set; }
        public Nullable<double> Kdv { get; set; }
        public Nullable<double> KuryeHakEdis { get; set; }
        public Nullable<bool> Faturali { get; set; }
        public Nullable<bool> Faturasiz { get; set; }
        public Nullable<bool> Cari { get; set; }
        public Nullable<bool> NakitKart { get; set; }
        public Nullable<bool> Kuryede { get; set; }
        public Nullable<bool> Bende { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string MusteriAd { get; set; }
        public string KuryeAd { get; set; }
        public string AlimAdresi { get; set; }
        public Nullable<double> Kazanc { get; set; }
        public string TeslimEdilenKisi { get; set; }
        public Nullable<int> SilinenKayitId { get; set; }
    }
}
