//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciTablosu
    {
        public int Id { get; set; }
        public string Kullaniciadi { get; set; }
        public string Sifre { get; set; }
        public string isimsoyisim { get; set; }
        public string E_Posta { get; set; }
        public string TcKimlikNo { get; set; }
        public string KullaniciFotograf { get; set; }
        public string TelefonNumarasi { get; set; }
        public string DogumYeri { get; set; }
        public string DogumTarihi { get; set; }
        public Nullable<bool> KayitEkle { get; set; }
        public Nullable<bool> MusteriEkle { get; set; }
        public Nullable<bool> KuryeEkle { get; set; }
        public Nullable<bool> Ayarlar { get; set; }
        public Nullable<bool> KullaniciDegistir { get; set; }
        public Nullable<bool> Tahsilatlar { get; set; }
        public Nullable<bool> Raporlama { get; set; }
        public Nullable<bool> KullaniciEkle { get; set; }
    }
}
