//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class KuryeOdemeTablosu
    {
        public int Id { get; set; }
        public string KuryeAdi { get; set; }
        public string KuryeTelefonNumarasi { get; set; }
        public Nullable<double> KuryeyeOlanBorc { get; set; }
        public Nullable<double> KuryeToplamBorc { get; set; }
        public Nullable<int> KayitTablosuId { get; set; }
    }
}
