//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KuryePeraVeriTabaniEntities : DbContext
    {
        public KuryePeraVeriTabaniEntities()
            : base("name=KuryePeraVeriTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MusteriTablosu> MusteriTablosu { get; set; }
        public virtual DbSet<PersonelTablosu> PersonelTablosu { get; set; }
        public virtual DbSet<KullaniciTablosu> KullaniciTablosu { get; set; }
        public virtual DbSet<KuryeOdemeTablosu> KuryeOdemeTablosu { get; set; }
        public virtual DbSet<KayitTablosuu> KayitTablosuu { get; set; }
        public virtual DbSet<MusteriOdemeTablosu> MusteriOdemeTablosu { get; set; }
    }
}
