//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriOdemeTablosu
    {
        public int Id { get; set; }
        public string MusteriAdi { get; set; }
        public string MusteriTelefon { get; set; }
        public Nullable<bool> OdemeDurumu { get; set; }
        public Nullable<double> MusteriToplamBorc { get; set; }
        public Nullable<int> KayitTablosuId { get; set; }
    }
}
