//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriTablosu
    {
        public int Id { get; set; }
        public string AdsoyadUnvan { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAdres { get; set; }
        public string MusteriEposta { get; set; }
        public string MusteriVergiNo { get; set; }
        public string YetkiliKisi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
