//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuryePera
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelTablosu
    {
        public int Id { get; set; }
        public string KuryeAdiSoyadi { get; set; }
        public string KuryeTelefonNumarasi { get; set; }
        public string KuryeMotorPlakasi { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    }
}
